name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install dependencies and test
        run: pnpm install-test --frozen-lockfile
      - name: Publish
        run: pnpm publish --ignore-scripts --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          single-commit: true
